name:         tapecart-browser
version:      1.4
synopsis:     Simple browser and loader for the tapecart
homepage:     https://github.com/alexkazik/tapecart-browser
license:      BSD3
license-file: LICENSE
author:       ALeX Kazik
maintainer:   alex@kazik.de
copyright:    2017 ALeX Kazik
category:     Compilers/Interpreters

executables:
  tapecart-browser:
    source-dirs: src
    ghc-options:
      - -Wall
      - -Werror
      - -O0
      - -rtsopts
    main: Main.hs
    dependencies:
      # assembler
      - asm-c64 == 0.6.*
      # other resources
      - base
      - base64-bytestring
      - bytestring
      - bzlib
      - directory
      - heredoc
      - text
      - vector
    default-extensions:
      - BinaryLiterals
      - OverloadedStrings
      - QuasiQuotes
      - TemplateHaskell
